#!/bin/bash
touch /home/ubuntu/startup.signal
pip install time
pip install boto3
cd /home/ubuntu
sudo mv cc-project1/app_server.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl start app_server
sudo systemctl enable app_server