#!/bin/bash
touch /home/ubuntu/startup.signal
pip install flask
pip install boto3
cd /home/ubuntu
sudo mv cc-project1/web_server.service /etc/systemd/system
sudo systemctl daemon-reload
sudo systemctl start web_server
sudo systemctl enable web_server